name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2

  # Navigation package
  go_router: ^6.5.8

  # Data packages
  shared_preferences: ^2.0.15

  # DI
  get_it: ^7.2.0

  # State managment packages
  flutter_bloc: ^8.1.2
  provider: ^6.0.3

  # Localization
  easy_localization: ^3.0.1

  # UI packages
  flutter_svg: ^2.0.5
  animated_text_kit: ^4.2.2

  # Encryption
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
        - asset: assets/fonts/Heebo-Medium.ttf
        - asset: assets/fonts/Heebo-Regular.ttf
        
