name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation package
  go_router: ^6.5.8

  # Data packages
  shared_preferences: ^2.0.15

  # DI
  get_it: ^7.2.0

  # State managment packages
  flutter_bloc: ^8.1.2
  provider: ^6.0.3

  # Localization
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
